// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx6KYFe9UzsywPWTYN_s2B_kNZ9LGH36g',
    appId: '1:576055934237:android:fa1bfe9daa57dac620f5f4',
    messagingSenderId: '576055934237',
    projectId: 'fittrack-61776',
    storageBucket: 'fittrack-61776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaXB-3FAe6Zx_C1bKiVYFgsFI2RrQDKKc',
    appId: '1:576055934237:ios:4844e837b5f5989720f5f4',
    messagingSenderId: '576055934237',
    projectId: 'fittrack-61776',
    storageBucket: 'fittrack-61776.appspot.com',
    androidClientId: '576055934237-vn1k003p9ao9b8ct0kd5tq16i2sb3ti1.apps.googleusercontent.com',
    iosClientId: '576055934237-pt74207afi4midd5nhkvffiabqb0u5sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaXB-3FAe6Zx_C1bKiVYFgsFI2RrQDKKc',
    appId: '1:576055934237:ios:e161e857114121b320f5f4',
    messagingSenderId: '576055934237',
    projectId: 'fittrack-61776',
    storageBucket: 'fittrack-61776.appspot.com',
    androidClientId: '576055934237-vn1k003p9ao9b8ct0kd5tq16i2sb3ti1.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupProject.RunnerTests',
  );
}
